service: trainingservice

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  region: us-east-1

  httpApi:
    cors:
      allowedOrigins:
        - "http://localhost:4200"
      allowedHeaders:
        - "*"
      exposedResponseHeaders:
        - "*"
      allowCredentials: true

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource:
            - "arn:aws:dynamodb:us-east-1:*:*"

functions:
  postTraining:
    handler: training.postTraining
    events:
      - httpApi:
          path: /trainings
          method: post

resources:
  Resources:
    TrainingTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: trainings
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: studentId
            AttributeType: S
          - AttributeName: trainerId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: StudentIdIndex
            KeySchema:
              - AttributeName: studentId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: TrainerIdIndex
            KeySchema:
              - AttributeName: trainerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: TypeIndex
            KeySchema:
              - AttributeName: type
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
